version: '3.1'

services:
  app:
    restart: always
    env_file:
      - .env
    build: ./
    command: bash -c "cd src && poetry run gunicorn app:app --timeout 120 --workers 4 --bind 0.0.0.0:8000 --log-level DEBUG --worker-class uvicorn.workers.UvicornWorker"
    ports:
      - "8000:8000"
    container_name: app

