version: '3.1'

services:
  app:
    restart: always
    volumes:
      - /home/simizzz/media/:/app/src/media/
      - /home/simizzz/.postgresql/root.crt:/app/src/root.crt
    env_file:
      - .env
    build: ./
    command: bash -c "cd src && poetry run uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    container_name: app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    user: root

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data

