version: '3.1'

services:
  app:
    restart: always
    volumes:
      - /home/simizzz/media/:/app/src/media/
      - /home/simizzz/.postgresql/root.crt:/app/src/root.crt
    env_file:
      - .env
    build: ./
    command: bash -c "cd src && poetry run uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    container_name: app

