"""change binary field

Revision ID: 0be5c2efb0f5
Revises: 1960c5fc0b33
Create Date: 2024-03-26 02:06:18.568634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be5c2efb0f5'
down_revision = '1960c5fc0b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
