"""change types to double

Revision ID: 0dfec975fb04
Revises: 222ea4b61fb3
Create Date: 2024-04-08 14:05:34.294806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfec975fb04'
down_revision = '222ea4b61fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
