"""add default value of tags

Revision ID: 123631de5f66
Revises: f12cbe344c58
Create Date: 2024-04-06 01:20:40.199777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123631de5f66'
down_revision = 'f12cbe344c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
