"""add new restaurants field

Revision ID: 1245b414d328
Revises: 8295bb59af33
Create Date: 2024-04-03 02:06:01.208021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1245b414d328'
down_revision = '8295bb59af33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('site', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('restaurants', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'phone_number')
    op.drop_column('restaurants', 'tags')
    op.drop_column('restaurants', 'site')
    op.drop_column('restaurants', 'address')
    # ### end Alembic commands ###
