"""add time fields

Revision ID: 222ea4b61fb3
Revises: 123631de5f66
Create Date: 2024-04-06 01:34:19.994204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222ea4b61fb3'
down_revision = '123631de5f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('open_from', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('open_to', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'open_to')
    op.drop_column('restaurants', 'open_from')
    # ### end Alembic commands ###
