"""change types to double

Revision ID: 29e1bb39ff9d
Revises: 0dfec975fb04
Create Date: 2024-04-08 14:05:46.817073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e1bb39ff9d'
down_revision = '0dfec975fb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('latitude', sa.REAL(), nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'latitude')
    # ### end Alembic commands ###
