"""Update latitude and longitude fields

Revision ID: 38d3c59c6b1e
Revises: 222ea4b61fb3
Create Date: 2024-04-08 12:49:06.103530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d3c59c6b1e'
down_revision = '222ea4b61fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'latitude',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('restaurants', 'longitude',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'longitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('restaurants', 'latitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
