"""update relarionship

Revision ID: 8295bb59af33
Revises: e4ca1a1f12d5
Create Date: 2024-03-31 05:48:46.452193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8295bb59af33'
down_revision = 'e4ca1a1f12d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
