"""add null parameter to restaurant fields

Revision ID: dea678593881
Revises: 763c36193ffc
Create Date: 2024-03-31 01:57:24.489253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea678593881'
down_revision = '763c36193ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
