"""update relarionship

Revision ID: e4ca1a1f12d5
Revises: 4781c52c0ba1
Create Date: 2024-03-31 05:48:30.557251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ca1a1f12d5'
down_revision = '4781c52c0ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
