"""add active field

Revision ID: f12cbe344c58
Revises: 672e8775f6a7
Create Date: 2024-04-03 02:11:19.787006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12cbe344c58'
down_revision = '672e8775f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
